export type InvitationTemplate = {
  id: string
  name: string
  category: "classique" | "nature" | "moderne" | "luxe" | "créatif"
  preview: string

  // Couleurs
  bgGradient: string
  primaryColor: string
  secondaryColor: string
  accentGradient: string

  // Enveloppe
  envelopeColor: string
  envelopeBorder: string
  sealGradient: string

  // Typographie
  titleFont: string
  titleStyle: string
  bodyFont: string

  // Layout & déco
  cardBorder: string
  cardBg: string
  decorPattern: "none" | "dots" | "lines" | "floral-border" | "geometric" | "art-deco"
  sectionDivider: string
  infoBg: string

  // Pass QR
  passHeaderGradient: string
  passAccent: string
  passBorder: string
  qrDark: string
  qrLight: string
}

export const templates: InvitationTemplate[] = [
  // ─── CLASSIQUE ─────────────────────────────────────────
  {
    id: "elegant-classic",
    name: "Élégant Classique",
    category: "classique",
    preview: "Noir & or, serif raffiné",
    bgGradient: "from-stone-50 via-amber-50/30 to-stone-100",
    primaryColor: "text-stone-900",
    secondaryColor: "text-amber-800",
    accentGradient: "from-amber-600 to-yellow-700",
    envelopeColor: "bg-stone-50",
    envelopeBorder: "border-amber-400",
    sealGradient: "from-amber-500 to-yellow-600",
    titleFont: "font-serif",
    titleStyle: "tracking-wider uppercase",
    bodyFont: "font-serif",
    cardBorder: "border-amber-300",
    cardBg: "bg-white",
    decorPattern: "lines",
    sectionDivider: "border-amber-200",
    infoBg: "bg-amber-50/60",
    passHeaderGradient: "from-stone-800 via-stone-700 to-amber-900",
    passAccent: "text-amber-600",
    passBorder: "border-amber-300",
    qrDark: "#78350f",
    qrLight: "#fffbeb",
  },
  {
    id: "romantic-rose",
    name: "Romance Rose",
    category: "classique",
    preview: "Rose blush, doux et tendre",
    bgGradient: "from-rose-50 via-pink-50 to-fuchsia-50",
    primaryColor: "text-rose-900",
    secondaryColor: "text-pink-700",
    accentGradient: "from-rose-500 to-pink-500",
    envelopeColor: "bg-rose-50",
    envelopeBorder: "border-rose-300",
    sealGradient: "from-rose-400 to-pink-500",
    titleFont: "font-serif",
    titleStyle: "italic",
    bodyFont: "font-serif",
    cardBorder: "border-rose-200",
    cardBg: "bg-white",
    decorPattern: "floral-border",
    sectionDivider: "border-rose-200",
    infoBg: "bg-rose-50/60",
    passHeaderGradient: "from-rose-500 via-pink-500 to-fuchsia-500",
    passAccent: "text-rose-600",
    passBorder: "border-rose-300",
    qrDark: "#be123c",
    qrLight: "#fff1f2",
  },
  {
    id: "vintage-sepia",
    name: "Vintage Sépia",
    category: "classique",
    preview: "Sépia & crème, rétro chic",
    bgGradient: "from-orange-50/50 via-amber-50/40 to-yellow-50/30",
    primaryColor: "text-amber-950",
    secondaryColor: "text-orange-800",
    accentGradient: "from-amber-700 to-orange-700",
    envelopeColor: "bg-orange-50/50",
    envelopeBorder: "border-orange-300",
    sealGradient: "from-orange-500 to-amber-600",
    titleFont: "font-serif",
    titleStyle: "tracking-widest uppercase text-sm",
    bodyFont: "font-serif",
    cardBorder: "border-orange-200",
    cardBg: "bg-white/80",
    decorPattern: "lines",
    sectionDivider: "border-orange-200",
    infoBg: "bg-orange-50/40",
    passHeaderGradient: "from-amber-800 via-orange-800 to-amber-900",
    passAccent: "text-orange-700",
    passBorder: "border-orange-300",
    qrDark: "#7c2d12",
    qrLight: "#fffbeb",
  },

  // ─── NATURE ────────────────────────────────────────────
  {
    id: "champetre-vert",
    name: "Champêtre",
    category: "nature",
    preview: "Vert sauge & crème, naturel",
    bgGradient: "from-green-50 via-emerald-50/30 to-lime-50/20",
    primaryColor: "text-green-900",
    secondaryColor: "text-emerald-700",
    accentGradient: "from-green-600 to-emerald-600",
    envelopeColor: "bg-green-50",
    envelopeBorder: "border-green-300",
    sealGradient: "from-green-500 to-emerald-500",
    titleFont: "font-serif",
    titleStyle: "italic",
    bodyFont: "font-sans",
    cardBorder: "border-green-200",
    cardBg: "bg-white",
    decorPattern: "floral-border",
    sectionDivider: "border-green-200",
    infoBg: "bg-green-50/60",
    passHeaderGradient: "from-green-600 via-emerald-600 to-teal-600",
    passAccent: "text-green-700",
    passBorder: "border-green-300",
    qrDark: "#14532d",
    qrLight: "#f0fdf4",
  },
  {
    id: "boheme-terracotta",
    name: "Bohème",
    category: "nature",
    preview: "Terracotta & sable chaud",
    bgGradient: "from-orange-50 via-amber-50/50 to-red-50/30",
    primaryColor: "text-orange-950",
    secondaryColor: "text-orange-700",
    accentGradient: "from-orange-500 to-red-500",
    envelopeColor: "bg-orange-50/70",
    envelopeBorder: "border-orange-300",
    sealGradient: "from-orange-400 to-red-500",
    titleFont: "font-sans",
    titleStyle: "font-light tracking-widest uppercase",
    bodyFont: "font-sans",
    cardBorder: "border-orange-200",
    cardBg: "bg-white/90",
    decorPattern: "dots",
    sectionDivider: "border-orange-200",
    infoBg: "bg-orange-50/50",
    passHeaderGradient: "from-orange-600 via-red-600 to-orange-700",
    passAccent: "text-orange-600",
    passBorder: "border-orange-300",
    qrDark: "#9a3412",
    qrLight: "#fff7ed",
  },
  {
    id: "tropical-paradise",
    name: "Tropical",
    category: "nature",
    preview: "Turquoise & corail, vibrant",
    bgGradient: "from-cyan-50 via-teal-50 to-emerald-50",
    primaryColor: "text-teal-900",
    secondaryColor: "text-cyan-700",
    accentGradient: "from-cyan-500 to-teal-500",
    envelopeColor: "bg-cyan-50",
    envelopeBorder: "border-cyan-300",
    sealGradient: "from-cyan-400 to-teal-500",
    titleFont: "font-sans",
    titleStyle: "font-bold",
    bodyFont: "font-sans",
    cardBorder: "border-cyan-200",
    cardBg: "bg-white",
    decorPattern: "none",
    sectionDivider: "border-cyan-200",
    infoBg: "bg-cyan-50/60",
    passHeaderGradient: "from-cyan-500 via-teal-500 to-emerald-500",
    passAccent: "text-teal-600",
    passBorder: "border-cyan-300",
    qrDark: "#134e4a",
    qrLight: "#ecfeff",
  },
  {
    id: "garden-lavande",
    name: "Jardin de Lavande",
    category: "nature",
    preview: "Violet lavande & vert tendre",
    bgGradient: "from-violet-50 via-purple-50/40 to-fuchsia-50/20",
    primaryColor: "text-violet-900",
    secondaryColor: "text-purple-700",
    accentGradient: "from-violet-500 to-purple-500",
    envelopeColor: "bg-violet-50",
    envelopeBorder: "border-violet-300",
    sealGradient: "from-violet-400 to-purple-500",
    titleFont: "font-serif",
    titleStyle: "italic",
    bodyFont: "font-sans",
    cardBorder: "border-violet-200",
    cardBg: "bg-white",
    decorPattern: "floral-border",
    sectionDivider: "border-violet-200",
    infoBg: "bg-violet-50/50",
    passHeaderGradient: "from-violet-500 via-purple-500 to-fuchsia-500",
    passAccent: "text-violet-600",
    passBorder: "border-violet-300",
    qrDark: "#4c1d95",
    qrLight: "#f5f3ff",
  },
  {
    id: "mediterraneen-azur",
    name: "Méditerranéen",
    category: "nature",
    preview: "Bleu azur & terre cuite",
    bgGradient: "from-sky-50 via-blue-50 to-amber-50/30",
    primaryColor: "text-sky-900",
    secondaryColor: "text-amber-700",
    accentGradient: "from-sky-500 to-blue-500",
    envelopeColor: "bg-sky-50",
    envelopeBorder: "border-sky-300",
    sealGradient: "from-amber-400 to-orange-500",
    titleFont: "font-serif",
    titleStyle: "",
    bodyFont: "font-sans",
    cardBorder: "border-sky-200",
    cardBg: "bg-white",
    decorPattern: "geometric",
    sectionDivider: "border-sky-200",
    infoBg: "bg-sky-50/60",
    passHeaderGradient: "from-sky-600 via-blue-600 to-sky-700",
    passAccent: "text-sky-700",
    passBorder: "border-sky-300",
    qrDark: "#0c4a6e",
    qrLight: "#f0f9ff",
  },

  // ─── MODERNE ───────────────────────────────────────────
  {
    id: "modern-minimal",
    name: "Moderne Minimal",
    category: "moderne",
    preview: "Noir & blanc, sans-serif épuré",
    bgGradient: "from-gray-50 via-white to-gray-50",
    primaryColor: "text-gray-900",
    secondaryColor: "text-gray-600",
    accentGradient: "from-gray-800 to-gray-900",
    envelopeColor: "bg-white",
    envelopeBorder: "border-gray-300",
    sealGradient: "from-gray-600 to-gray-800",
    titleFont: "font-sans",
    titleStyle: "font-light tracking-[0.3em] uppercase",
    bodyFont: "font-sans",
    cardBorder: "border-gray-200",
    cardBg: "bg-white",
    decorPattern: "lines",
    sectionDivider: "border-gray-200",
    infoBg: "bg-gray-50",
    passHeaderGradient: "from-gray-800 via-gray-900 to-black",
    passAccent: "text-gray-700",
    passBorder: "border-gray-300",
    qrDark: "#1f2937",
    qrLight: "#f9fafb",
  },
  {
    id: "geometric-blush",
    name: "Géométrique",
    category: "moderne",
    preview: "Rose gold & motifs géométriques",
    bgGradient: "from-pink-50/50 via-rose-50/30 to-amber-50/20",
    primaryColor: "text-pink-900",
    secondaryColor: "text-pink-600",
    accentGradient: "from-pink-400 to-rose-500",
    envelopeColor: "bg-pink-50/60",
    envelopeBorder: "border-pink-300",
    sealGradient: "from-pink-400 to-amber-400",
    titleFont: "font-sans",
    titleStyle: "font-semibold tracking-wider uppercase",
    bodyFont: "font-sans",
    cardBorder: "border-pink-200",
    cardBg: "bg-white/90",
    decorPattern: "geometric",
    sectionDivider: "border-pink-200",
    infoBg: "bg-pink-50/40",
    passHeaderGradient: "from-pink-500 via-rose-500 to-amber-500",
    passAccent: "text-pink-600",
    passBorder: "border-pink-300",
    qrDark: "#9d174d",
    qrLight: "#fdf2f8",
  },
  {
    id: "scandinave-frost",
    name: "Scandinave",
    category: "moderne",
    preview: "Bleu glacé & blanc, minimaliste",
    bgGradient: "from-blue-50/50 via-slate-50 to-sky-50/30",
    primaryColor: "text-slate-800",
    secondaryColor: "text-blue-600",
    accentGradient: "from-blue-400 to-sky-500",
    envelopeColor: "bg-blue-50/50",
    envelopeBorder: "border-blue-200",
    sealGradient: "from-blue-400 to-sky-400",
    titleFont: "font-sans",
    titleStyle: "font-extralight tracking-[0.2em]",
    bodyFont: "font-sans",
    cardBorder: "border-blue-100",
    cardBg: "bg-white/80",
    decorPattern: "dots",
    sectionDivider: "border-blue-100",
    infoBg: "bg-blue-50/40",
    passHeaderGradient: "from-blue-500 via-sky-500 to-blue-400",
    passAccent: "text-blue-600",
    passBorder: "border-blue-200",
    qrDark: "#1e3a5f",
    qrLight: "#eff6ff",
  },

  // ─── LUXE ──────────────────────────────────────────────
  {
    id: "art-deco-gatsby",
    name: "Art Déco",
    category: "luxe",
    preview: "Or & noir, années 1920",
    bgGradient: "from-yellow-50/30 via-stone-50 to-amber-50/20",
    primaryColor: "text-stone-900",
    secondaryColor: "text-amber-700",
    accentGradient: "from-yellow-600 to-amber-700",
    envelopeColor: "bg-stone-50",
    envelopeBorder: "border-yellow-500",
    sealGradient: "from-yellow-500 to-amber-600",
    titleFont: "font-serif",
    titleStyle: "tracking-[0.4em] uppercase font-bold",
    bodyFont: "font-serif",
    cardBorder: "border-yellow-400",
    cardBg: "bg-white",
    decorPattern: "art-deco",
    sectionDivider: "border-yellow-400",
    infoBg: "bg-yellow-50/40",
    passHeaderGradient: "from-stone-900 via-stone-800 to-yellow-900",
    passAccent: "text-yellow-600",
    passBorder: "border-yellow-400",
    qrDark: "#713f12",
    qrLight: "#fefce8",
  },
  {
    id: "royal-navy",
    name: "Royal Navy",
    category: "luxe",
    preview: "Bleu marine & or, majestueux",
    bgGradient: "from-blue-50/30 via-indigo-50/20 to-slate-50",
    primaryColor: "text-blue-950",
    secondaryColor: "text-indigo-700",
    accentGradient: "from-blue-700 to-indigo-700",
    envelopeColor: "bg-blue-50/50",
    envelopeBorder: "border-blue-400",
    sealGradient: "from-yellow-500 to-amber-500",
    titleFont: "font-serif",
    titleStyle: "tracking-wider uppercase",
    bodyFont: "font-serif",
    cardBorder: "border-blue-300",
    cardBg: "bg-white",
    decorPattern: "lines",
    sectionDivider: "border-blue-300",
    infoBg: "bg-blue-50/50",
    passHeaderGradient: "from-blue-900 via-indigo-900 to-blue-800",
    passAccent: "text-blue-800",
    passBorder: "border-blue-400",
    qrDark: "#1e3a8a",
    qrLight: "#eff6ff",
  },
  {
    id: "velvet-burgundy",
    name: "Velours Bordeaux",
    category: "luxe",
    preview: "Bordeaux & or, opulent",
    bgGradient: "from-red-50/40 via-rose-50/20 to-amber-50/20",
    primaryColor: "text-red-950",
    secondaryColor: "text-red-800",
    accentGradient: "from-red-700 to-rose-700",
    envelopeColor: "bg-red-50/50",
    envelopeBorder: "border-red-400",
    sealGradient: "from-red-600 to-rose-600",
    titleFont: "font-serif",
    titleStyle: "italic tracking-wide",
    bodyFont: "font-serif",
    cardBorder: "border-red-300",
    cardBg: "bg-white",
    decorPattern: "floral-border",
    sectionDivider: "border-red-300",
    infoBg: "bg-red-50/40",
    passHeaderGradient: "from-red-800 via-rose-800 to-red-900",
    passAccent: "text-red-700",
    passBorder: "border-red-400",
    qrDark: "#7f1d1d",
    qrLight: "#fef2f2",
  },
  {
    id: "orient-dore",
    name: "Oriental Doré",
    category: "luxe",
    preview: "Or & émeraude, ornementé",
    bgGradient: "from-emerald-50/30 via-amber-50/20 to-green-50/20",
    primaryColor: "text-emerald-950",
    secondaryColor: "text-amber-700",
    accentGradient: "from-emerald-600 to-teal-600",
    envelopeColor: "bg-emerald-50/50",
    envelopeBorder: "border-amber-400",
    sealGradient: "from-amber-500 to-yellow-500",
    titleFont: "font-serif",
    titleStyle: "tracking-wider",
    bodyFont: "font-serif",
    cardBorder: "border-amber-300",
    cardBg: "bg-white",
    decorPattern: "geometric",
    sectionDivider: "border-amber-300",
    infoBg: "bg-emerald-50/40",
    passHeaderGradient: "from-emerald-800 via-teal-800 to-emerald-900",
    passAccent: "text-emerald-700",
    passBorder: "border-amber-400",
    qrDark: "#064e3b",
    qrLight: "#ecfdf5",
  },

  // ─── CRÉATIF ───────────────────────────────────────────
  {
    id: "dark-moody",
    name: "Sombre & Mystérieux",
    category: "créatif",
    preview: "Noir & violet, dramatique",
    bgGradient: "from-slate-100 via-purple-50/30 to-slate-100",
    primaryColor: "text-slate-900",
    secondaryColor: "text-purple-700",
    accentGradient: "from-purple-600 to-violet-600",
    envelopeColor: "bg-slate-100",
    envelopeBorder: "border-purple-400",
    sealGradient: "from-purple-500 to-violet-600",
    titleFont: "font-serif",
    titleStyle: "tracking-[0.3em] uppercase",
    bodyFont: "font-sans",
    cardBorder: "border-purple-300",
    cardBg: "bg-white/90",
    decorPattern: "dots",
    sectionDivider: "border-purple-300",
    infoBg: "bg-purple-50/40",
    passHeaderGradient: "from-slate-900 via-purple-900 to-violet-900",
    passAccent: "text-purple-600",
    passBorder: "border-purple-400",
    qrDark: "#581c87",
    qrLight: "#faf5ff",
  },
  {
    id: "watercolor-sunset",
    name: "Aquarelle Sunset",
    category: "créatif",
    preview: "Orange & rose, artistique",
    bgGradient: "from-orange-50 via-rose-50/50 to-pink-50/30",
    primaryColor: "text-orange-900",
    secondaryColor: "text-rose-700",
    accentGradient: "from-orange-400 to-rose-500",
    envelopeColor: "bg-orange-50/60",
    envelopeBorder: "border-orange-300",
    sealGradient: "from-orange-400 to-rose-400",
    titleFont: "font-serif",
    titleStyle: "italic font-light",
    bodyFont: "font-sans",
    cardBorder: "border-orange-200",
    cardBg: "bg-white/80",
    decorPattern: "none",
    sectionDivider: "border-orange-200",
    infoBg: "bg-orange-50/40",
    passHeaderGradient: "from-orange-500 via-rose-500 to-pink-500",
    passAccent: "text-orange-600",
    passBorder: "border-orange-300",
    qrDark: "#9a3412",
    qrLight: "#fff7ed",
  },
  {
    id: "pastel-rainbow",
    name: "Pastel Arc-en-ciel",
    category: "créatif",
    preview: "Multi-pastel, joyeux & festif",
    bgGradient: "from-pink-50 via-sky-50 to-lime-50",
    primaryColor: "text-gray-800",
    secondaryColor: "text-pink-600",
    accentGradient: "from-pink-400 via-violet-400 to-sky-400",
    envelopeColor: "bg-pink-50/50",
    envelopeBorder: "border-pink-300",
    sealGradient: "from-pink-400 via-yellow-400 to-sky-400",
    titleFont: "font-sans",
    titleStyle: "font-bold",
    bodyFont: "font-sans",
    cardBorder: "border-pink-200",
    cardBg: "bg-white/90",
    decorPattern: "dots",
    sectionDivider: "border-violet-200",
    infoBg: "bg-pink-50/40",
    passHeaderGradient: "from-pink-400 via-violet-500 to-sky-400",
    passAccent: "text-violet-600",
    passBorder: "border-violet-300",
    qrDark: "#6d28d9",
    qrLight: "#faf5ff",
  },
]

export function getTemplate(id: string): InvitationTemplate {
  return templates.find((t) => t.id === id) ?? templates[0]
}

export const categoryLabels: Record<string, string> = {
  classique: "Classique",
  nature: "Nature",
  moderne: "Moderne",
  luxe: "Luxe",
  créatif: "Créatif",
}

export type InvitationCustom = {
  message?: string
  program?: { time: string; label: string }[]
  hideCountdown?: boolean
  hideProgram?: boolean
}
